-- Generated by matugen. Do not edit — overwritten on every theme apply.
--
-- conf/looks.lua requires this module and falls back to a built-in palette if
-- it is missing, which is what happens on a fresh clone before
-- `install.sh --theme` has run.
--
-- Hyprland wants rgba(rrggbbaa); matugen gives the hex without the leading #
-- via hex_stripped, and the alpha is appended here.

return {
  primary   = "rgba({{colors.primary.default.hex_stripped}}ee)",
  tertiary  = "rgba({{colors.tertiary.default.hex_stripped}}ee)",
  outline   = "rgba({{colors.outline.default.hex_stripped}}59)",
  surface   = "rgba({{colors.surface.default.hex_stripped}}ff)",
  onSurface = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
  error     = "rgba({{colors.error.default.hex_stripped}}ee)",
}
