-- Gaps, borders, blur, shadows, animations.
-- Numbers come from DESIGN.md §2 and §3. Change them there too.

-- Border colours are generated by matugen into conf/colors.lua. That file is
-- gitignored and does not exist until `install.sh --theme` has run, so fall
-- back to something neutral rather than dropping the whole module.
local ok, colors = pcall(require, "conf.colors")
if not ok then
  colors = {
    primary  = "rgba(cba6f7ee)",
    tertiary = "rgba(94e2d5ee)",
    outline  = "rgba(6c708659)",
  }
end

hl.config({
  general = {
    gaps_in  = 6,
    gaps_out = 6,

    border_size = 2,

    col = {
      -- 45° gradient, primary -> tertiary. The active window border is the one
      -- place the wallpaper's colour shows up in the compositor itself.
      active_border   = { colors = { colors.primary, colors.tertiary }, angle = 45 },
      inactive_border = colors.outline,
    },

    -- Dragging a border to resize is convenient but makes the 6px gap a hit
    -- target, which steals clicks meant for the window underneath.
    resize_on_border = false,

    allow_tearing = false,
    layout = "dwindle",
  },

  decoration = {
    rounding = 12,
    -- 2 is a circular corner; higher values approach a squircle. 2.4 reads
    -- closer to the shell's island corners without looking obviously blobby.
    rounding_power = 2.4,

    -- Window opacity stays at 1.0 on purpose. Fading a whole window fades its
    -- TEXT as well, which is what made v1's terminal look washed out. The
    -- terminal's own background_opacity handles translucency, leaving glyphs
    -- fully opaque over the blur.
    active_opacity   = 1.0,
    inactive_opacity = 1.0,

    blur = {
      enabled    = true,
      size       = 6,
      passes     = 3,
      noise      = 0.02,
      contrast   = 1.0,
      brightness = 0.9,
      -- xray makes floating windows sample the WALLPAPER instead of the window
      -- behind them, so a floating terminal over a browser looks opaque and
      -- wrong. It is cheaper. It is off anyway.
      xray       = false,
    },

    shadow = {
      enabled      = true,
      range        = 12,
      render_power = 3,
      color        = "rgba(00000044)",
    },
  },

  dwindle = {
    -- New window keeps the split direction of the focused one rather than
    -- always alternating — more predictable when you are building a layout.
    preserve_split = true,
    -- NOT `pseudotile`: that is not a dwindle option. Pseudotiling is a
    -- per-window state, set by the SUPER+SHIFT+P dispatcher or a window rule.
  },

  misc = {
    -- No Hyprland logo on an empty workspace, no "you have updates" banner.
    disable_hyprland_logo     = true,
    disable_splash_rendering  = true,
    force_default_wallpaper   = 0,
    -- Focus follows the window you open, not the mouse.
    focus_on_activate         = true,
    -- NOT `vfr`: it lives under `debug`, not `misc`, and defaults to true
    -- ("heavily recommended to leave enabled"). Setting it here is both wrong
    -- and unnecessary.
  },

  animations = { enabled = true },
})

-- Curves. easeOutQuint is the same curve the shell uses for the notch
-- expanding (DESIGN.md §3), so window motion and shell motion feel related.
hl.curve("easeOutQuint",  { type = "bezier", points = { { 0.22, 1 },   { 0.36, 1 } } })
hl.curve("easeInQuint",   { type = "bezier", points = { { 0.64, 0 },   { 0.78, 0 } } })
hl.curve("linear",        { type = "bezier", points = { { 0, 0 },      { 1, 1 } } })
hl.curve("softSpring",    { type = "spring", mass = 1, stiffness = 220, dampening = 24 })

-- Speeds are in ds (1ds = 100ms). Opening is slower than closing, for the same
-- reason the notch expands slower than it collapses: arriving should be
-- noticed, leaving should get out of the way.
hl.animation({ leaf = "global",     enabled = true, speed = 6,   bezier = "easeOutQuint" })
hl.animation({ leaf = "border",     enabled = true, speed = 4,   bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",    enabled = true, speed = 4.5, spring = "softSpring" })
hl.animation({ leaf = "windowsIn",  enabled = true, speed = 4,   spring = "softSpring", style = "popin 92%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2,   bezier = "easeInQuint", style = "popin 92%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 2.6, bezier = "linear" })
hl.animation({ leaf = "layers",     enabled = true, speed = 3,   bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2.6, bezier = "easeOutQuint", style = "slidefade 15%" })
